# AUT_Config.yaml
environment:
  dev:
    kafka_host: "dev-kafka-host"
    kafka_topic: "dev-kafka-topic"
    databricks_token_vault_path: "path/to/databricks/dev/token"
    databricks_host: "dev-databricks-host"
    adls_account: "dev-adls-account"
    use_hashicorp_vault: "Yes"

  INT:
    kafka_host: "dev-kafka-host"
    kafka_topic: "dev-kafka-topic"
    databricks_token_vault_path: "path/to/databricks/int/token"
    databricks_host: "dev-databricks-host"
    adls_account: "dev-adls-account"
    use_hashicorp_vault: "Yes"

  qa:
    kafka_host: "qa-kafka-host"
    kafka_topic: "qa-kafka-topic"
    databricks_token_vault_path: "path/to/databricks/qa/token"
    databricks_host: "qa-databricks-host"
    adls_account: "qa-adls-account"
    use_hashicorp_vault: "Yes"
  prod:
    kafka_host: "prod-kafka-host"
    kafka_topic: "prod-kafka-topic"
    databricks_token_vault_path: "path/to/databricks/prod/token"
    databricks_host: "prod-databricks-host"
    adls_account: "prod-adls-account"
    use_hashicorp_vault: "Yes"

vault:
  url: "http://vault.example.com"
  token_path: "path/to/vault/token"

splunk/creds:
  username_vault_path: "path/to/splunk/username"
  password_vault_path: "path/to/splunk/password"

databricks/creds:
  token_vault_path: "path/to/databricks/token"
